//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cliente.ServiceReferenceWSEtiquetas {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Response", Namespace="http://www.tecnologisticaconsultores.com/")]
    [System.SerializableAttribute()]
    public partial class Response : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string messageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private global::Cliente.ServiceReferenceWSEtiquetas.Archivo[] ArchivosField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string message {
            get {
                return this.messageField;
            }
            set {
                if ((object.ReferenceEquals(this.messageField, value) != true)) {
                    this.messageField = value;
                    this.RaisePropertyChanged("message");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public global::Cliente.ServiceReferenceWSEtiquetas.Archivo[] Archivos {
            get {
                return this.ArchivosField;
            }
            set {
                if ((object.ReferenceEquals(this.ArchivosField, value) != true)) {
                    this.ArchivosField = value;
                    this.RaisePropertyChanged("Archivos");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Archivo", Namespace="http://www.tecnologisticaconsultores.com/")]
    [System.SerializableAttribute()]
    public partial class Archivo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string base64Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string urlField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string base64 {
            get {
                return this.base64Field;
            }
            set {
                if ((object.ReferenceEquals(this.base64Field, value) != true)) {
                    this.base64Field = value;
                    this.RaisePropertyChanged("base64");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                if ((object.ReferenceEquals(this.nombreField, value) != true)) {
                    this.nombreField = value;
                    this.RaisePropertyChanged("nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string url {
            get {
                return this.urlField;
            }
            set {
                if ((object.ReferenceEquals(this.urlField, value) != true)) {
                    this.urlField = value;
                    this.RaisePropertyChanged("url");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.tecnologisticaconsultores.com/", ConfigurationName="ServiceReferenceWSEtiquetas.WSEtiquetasSoap")]
    public interface WSEtiquetasSoap {
        
        // CODEGEN: Generating message contract since element name user from namespace http://www.tecnologisticaconsultores.com/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://www.tecnologisticaconsultores.com/EtiquetasWS", ReplyAction="*")]
        global::Cliente.ServiceReferenceWSEtiquetas.EtiquetasWSResponse EtiquetasWS(global::Cliente.ServiceReferenceWSEtiquetas.EtiquetasWSRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.tecnologisticaconsultores.com/EtiquetasWS", ReplyAction="*")]
        System.Threading.Tasks.Task<global::Cliente.ServiceReferenceWSEtiquetas.EtiquetasWSResponse> EtiquetasWSAsync(global::Cliente.ServiceReferenceWSEtiquetas.EtiquetasWSRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class EtiquetasWSRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="EtiquetasWS", Namespace="http://www.tecnologisticaconsultores.com/", Order=0)]
        public global::Cliente.ServiceReferenceWSEtiquetas.EtiquetasWSRequestBody Body;
        
        public EtiquetasWSRequest() {
        }
        
        public EtiquetasWSRequest(global::Cliente.ServiceReferenceWSEtiquetas.EtiquetasWSRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.tecnologisticaconsultores.com/")]
    public partial class EtiquetasWSRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string user;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string IDRemito;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string cliente;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string format;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string size;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
        public int separarPorDocumento;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string template;
        
        public EtiquetasWSRequestBody() {
        }
        
        public EtiquetasWSRequestBody(string user, string password, string IDRemito, string cliente, string format, string size, int separarPorDocumento, string template) {
            this.user = user;
            this.password = password;
            this.IDRemito = IDRemito;
            this.cliente = cliente;
            this.format = format;
            this.size = size;
            this.separarPorDocumento = separarPorDocumento;
            this.template = template;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class EtiquetasWSResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="EtiquetasWSResponse", Namespace="http://www.tecnologisticaconsultores.com/", Order=0)]
        public global::Cliente.ServiceReferenceWSEtiquetas.EtiquetasWSResponseBody Body;
        
        public EtiquetasWSResponse() {
        }
        
        public EtiquetasWSResponse(global::Cliente.ServiceReferenceWSEtiquetas.EtiquetasWSResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.tecnologisticaconsultores.com/")]
    public partial class EtiquetasWSResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public global::Cliente.ServiceReferenceWSEtiquetas.Response EtiquetasWSResult;
        
        public EtiquetasWSResponseBody() {
        }
        
        public EtiquetasWSResponseBody(global::Cliente.ServiceReferenceWSEtiquetas.Response EtiquetasWSResult) {
            this.EtiquetasWSResult = EtiquetasWSResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WSEtiquetasSoapChannel : global::Cliente.ServiceReferenceWSEtiquetas.WSEtiquetasSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WSEtiquetasSoapClient : System.ServiceModel.ClientBase<global::Cliente.ServiceReferenceWSEtiquetas.WSEtiquetasSoap>, global::Cliente.ServiceReferenceWSEtiquetas.WSEtiquetasSoap {
        
        public WSEtiquetasSoapClient() {
        }
        
        public WSEtiquetasSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WSEtiquetasSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WSEtiquetasSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WSEtiquetasSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        global::Cliente.ServiceReferenceWSEtiquetas.EtiquetasWSResponse global::Cliente.ServiceReferenceWSEtiquetas.WSEtiquetasSoap.EtiquetasWS(global::Cliente.ServiceReferenceWSEtiquetas.EtiquetasWSRequest request) {
            return base.Channel.EtiquetasWS(request);
        }
        
        public global::Cliente.ServiceReferenceWSEtiquetas.Response EtiquetasWS(string user, string password, string IDRemito, string cliente, string format, string size, int separarPorDocumento, string template) {
            global::Cliente.ServiceReferenceWSEtiquetas.EtiquetasWSRequest inValue = new global::Cliente.ServiceReferenceWSEtiquetas.EtiquetasWSRequest();
            inValue.Body = new global::Cliente.ServiceReferenceWSEtiquetas.EtiquetasWSRequestBody();
            inValue.Body.user = user;
            inValue.Body.password = password;
            inValue.Body.IDRemito = IDRemito;
            inValue.Body.cliente = cliente;
            inValue.Body.format = format;
            inValue.Body.size = size;
            inValue.Body.separarPorDocumento = separarPorDocumento;
            inValue.Body.template = template;
            global::Cliente.ServiceReferenceWSEtiquetas.EtiquetasWSResponse retVal = ((global::Cliente.ServiceReferenceWSEtiquetas.WSEtiquetasSoap)(this)).EtiquetasWS(inValue);
            return retVal.Body.EtiquetasWSResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<global::Cliente.ServiceReferenceWSEtiquetas.EtiquetasWSResponse> global::Cliente.ServiceReferenceWSEtiquetas.WSEtiquetasSoap.EtiquetasWSAsync(global::Cliente.ServiceReferenceWSEtiquetas.EtiquetasWSRequest request) {
            return base.Channel.EtiquetasWSAsync(request);
        }
        
        public System.Threading.Tasks.Task<global::Cliente.ServiceReferenceWSEtiquetas.EtiquetasWSResponse> EtiquetasWSAsync(string user, string password, string IDRemito, string cliente, string format, string size, int separarPorDocumento, string template) {
            global::Cliente.ServiceReferenceWSEtiquetas.EtiquetasWSRequest inValue = new global::Cliente.ServiceReferenceWSEtiquetas.EtiquetasWSRequest();
            inValue.Body = new global::Cliente.ServiceReferenceWSEtiquetas.EtiquetasWSRequestBody();
            inValue.Body.user = user;
            inValue.Body.password = password;
            inValue.Body.IDRemito = IDRemito;
            inValue.Body.cliente = cliente;
            inValue.Body.format = format;
            inValue.Body.size = size;
            inValue.Body.separarPorDocumento = separarPorDocumento;
            inValue.Body.template = template;
            return ((global::Cliente.ServiceReferenceWSEtiquetas.WSEtiquetasSoap)(this)).EtiquetasWSAsync(inValue);
        }
    }
}
